version: '3.8'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword # Change this to a secure password
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin # Change this to a secure password
    depends_on:
      - influxdb
    restart: always

  monitoring-and-automation-backend: # Name of the backend service
    build: backend
    environment:
      INFLUX_TOKEN: ${INFLUX_TOKEN}
    ports:
      - "8002:8000"
    depends_on:
      - influxdb
      - grafana
    
  monitoring-and-automation-frontend: # Name of the frontend service
    build: frontend/monitoring-and-automation
    ports: 
      - "10003:80"
    depends_on:
      - monitoring-and-automation-backend

volumes:
  influxdb_data:
  grafana_data: